### PR TITLE
Update for Django 1.9

### PR DESCRIPTION
**Pull request by sp-niemand**
In Django 1.9 FileWrapper alias was removed:
https://github.com/django/django/commit/bbe28496d32f76ca161f5c33787d6ad62267fcc6#diff-f6d1c75ec606389da5af6558bf57f171L15

### CODE REVIEW

**Comment by sp-niemand** [comment]
The tests failing don't have anything to do with the fix, it being very small and simple.

**Comment by sp-niemand** [comment]
https://github.com/sp-niemand/db_file_storage/commit/a86c8581c75f624a9d705deefa0dafa2d56d4f2a
This is safer to use, than just python `urlencode`. I got an error with non-ASCII symbols in file names with the old version.

**Comment by victor-o-silva** [comment]
Sweet! Thanks a lot!
And sorry for taking so long to merge it.

**Comment by sp-niemand** [comment]
@victor-o-silva Thank you for the package :) Used it.

**Pull request merged**
